nt_stuff/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('stuff.urls')),
]

admin.site.site_header = "StuFF at the Nottingham New Theatre"
admin.site.site_title = "StuFF Admin"

stuff/urls.py
from django.urls import include, path 

from . import views 

app_name = 'stuff'
urlpatterns = [

	# Authentication
	#/login
	path('login/', views.stuffLoginView.as_view(), name='stuffLogin'),
	#/logout
	path('logout/', views.stuffLogoutView.as_view(), name='stuffLogout'),

	# Shows 
	path('', views.ShowView.as_view(), name='stuffCurrentShows'),
	path('show/', views.ShowView.as_view(), name='stuffCurrentShows'),
	path('show/all', views.ShowArchiveView.as_view(), name='stuffShowArchive'),
	path('show/<int:pk>/', views.InductionView.as_view(), name='stuffInduction'),
	path('show/<int:pk>/', include([
		path('start/', views.InductionNewView.as_view(), name='stuffInductionNew'),
		path('edit/', views.InductionEditView.as_view(), name='stuffInductionEdit'),
		path('requirements/', views.RequirementsView.as_view(), name='stuffRequirements'),
		path('requirements/new', views.RequirementsNewView.as_view(), name='stuffRequirementsNew'),
		path('requirements/edit', views.RequirementsEditView.as_view(), name='stuffRequirementsEdit'),
		path('venue/', views.VenueReportView.as_view(), name='stuffVenueReport'),
		path('venue/new', views.VenueReportNewView.as_view(), name='stuffVenueReportNew'),
		path('venue/edit', views.VenueReportEditView.as_view(), name='stuffVenueReportEdit'),
		path('foh/', views.FOHReportView.as_view(), name='stuffFOHReport'),
		path('foh/new', views.FOHReportNewView.as_view(), name='stuffFOHReportNew'),
		path('foh/edit', views.FOHReportEditView.as_view(), name='stuffFOHReportEdit'),
	])),

	path('company/<int:pk>', views.CompanyView.as_view(), name='stuffCompanySingle'),

	path('requirements', views.RequirementsNewView.as_view(), name='stuffRequirementsBlankNew'),
	path('induction', views.InductionNewView.as_view(), name='stuffInductionBlankNew'),
	path('venue', views.VenueReportNewView.as_view(), name='stuffVenueReportBlankNew'),
	path('foh', views.FOHReportNewView.as_view(), name='stuffFOHReportBlankNew'),

	path('log/', views.LogReportListView.as_view(), name='stuffLogList'),
	path('log/<int:pk>/', views.LogReportSingleView.as_view(), name='stuffLogSingle'),
	path('log/<int:pk>/edit', views.LogReportEditView.as_view(), name='stuffLogEdit'),
	path('log/new/', views.LogReportCreateView.as_view(), name='stuffLogNew'),

	path('log/day/', views.DayReportListView.as_view(), name='stuffDayReportList'),
	path('log/day/<int:pk>', views.DayReportView.as_view(), name='stuffDayReport'),
	path('log/day/<int:pk>/edit', views.DayReportEditView.as_view(), name='stuffDayReportEdit'),
	path('log/day/new', views.DayReportCreateView.as_view(), name='stuffDayReportNew'),

	# Festival Reports (TBA)
]
handler404 = views.PageNotFoundView.as_view()

stuff/models.py
import datetime

from django.db import models
from django.utils import timezone 

# Create your models here.

class Venue(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name 

class ShowStop(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		verbose_name = "Show Stop Trigger"

	def __str__(self):
		return self.name 

class Company(models.Model):
	class Meta:
		verbose_name_plural = "Companies"
	name = models.CharField(
		max_length=250,
		unique=True
	)

	def company_shows(self):
		return Show.objects.filter(company_name=self)

	def __str__(self):
		return self.name 

class Show(models.Model):
	class Meta:
		ordering = ['show_date','performance_start']
	company_name = models.ForeignKey(
		Company,
		on_delete=models.DO_NOTHING
	)

	show_name = models.CharField(max_length=250)

	performance_venue = models.ForeignKey(
		Venue,
		default=None,
		blank=True,
		on_delete=models.DO_NOTHING
	)

	ticketing_id = models.IntegerField(
		unique=True,
		blank=True,
		null=True,
		help_text = 'Go to the <a href="https://ticketing.newtheatre.org.uk/" target="_blank">Ticketing Site</a>, select a show and use the first number in the URL: /SHOWID/0.'
	)

	show_date = models.DateField(blank=True)
	slot_start = models.TimeField(blank=True)
	slot_end = models.TimeField(blank=True)
	performance_start = models.TimeField(blank=True)
	performance_end = models.TimeField(blank=True)

	def has_requirements(self):
		has_requirements = Requirement.objects.filter(show_name=self)
		return has_requirements

	def has_induction(self):
		has_induction = Induction.objects.filter(show_name=self)
		return has_induction

	def has_foh_report(self):
		has_foh_report = FOHReport.objects.filter(show_name=self)
		return has_foh_report

	def has_venue_report(self):
		has_venue_report = VenueReport.objects.filter(show_name=self)
		return has_venue_report

	def __str__(self):
		display_string = '"' + str(self.show_name) + '" by ' + str(self.company_name)
		return display_string

class Requirement(models.Model):
	class Meta:
		verbose_name = "Requirements Form"
		verbose_name_plural = "Requirements Forms"

	show_name = models.OneToOneField(
		Show,
		on_delete = models.CASCADE,
	)
	# Theatre
	using_workshop = models.BooleanField(
		default=False
	)
	using_storage = models.BooleanField(
		default=False
	)
	storage_notes = models.CharField(
		default='None',
		max_length=250,
		help_text = "What is this company bringing to store?",
	)
	using_props = models.BooleanField(default=False)
	prop_notes = models.CharField(
		default='None',
		max_length=250,
		help_text = "What props/costume is this show using from the Theatre?"
	)
	rigging = models.CharField(
		default='None',
		max_length = 250,
		help_text = "Any additional rigging that is required."
	)
	effects = models.CharField(
		default='None',
		max_length=200,
		help_text = "Effects used in this show, eg: strobe, smoke, haze, pyro."
	)
	fire_alarm_disabled = models.BooleanField(default=False)
	theatre_notes = models.TextField(blank=True)

	# Set/Staging
	seating_layout = models.CharField(
		choices = (
			('E', 'End-on'),
			('T', 'Thrust'),
			('R', 'In the round'),
			('O', 'Other (add in notes)'),
		),
		default = 'E',
		max_length = 50
	)
	set_details = models.CharField(
		default='No set',
		max_length=200
	)
	set_notes = models.TextField(blank=True)

	# Tech
	lighting = models.CharField(
		max_length=250,
		default='None',
	)
	sound = models.CharField(
		max_length=250,
		default='None',
	)
	microphones = models.IntegerField(default=0, help_text="How many microphones are being used?")
	video = models.CharField(
		max_length=250,
		default = 'None',
	)
	projector_screen = models.BooleanField(default=False, help_text="Does this show require a projector screen?")
	tech_notes = models.TextField(blank=True)

	def __str__(self):
		display_string = "Requirements form for " + str(self.show_name)
		return display_string

class Induction(models.Model):
	show_name = models.OneToOneField(
		Show,
		on_delete=models.CASCADE, 
	)
	author = models.CharField(
		max_length=100,
		help_text="Who is filling this form out?",
		# Should make this relate to a group of users 
	)
	show_member = models.CharField(
		max_length=100,
		help_text="Who are you speaking to?"
	)
	show_phone = models.IntegerField(
		help_text="What is their phone number?"
	) 
	show_role = models.CharField(
		max_length = 30,
		help_text="What is their role in the company?",
		blank=True
	)
	latecomers = models.CharField(
		max_length = 30,
		help_text = "May latecomers be permitted?",
		choices = (
			('N', 'No latecomers'),
			('Y', 'Latecomers up to the first 15 minutes of the show'),
		),
		default = 'N'
	)
	comps = models.IntegerField(
		default = 0
	)
	comp_list = models.TextField(
		blank=True,
		help_text = "Please list the full names of all people receiving complimentary tickets."
	)
	minimum_audience = models.CharField(
		default='No minimum',
		max_length=255,
		help_text = "Is there a minimum audience to which this company will perform?"
	)

	show_end = models.CharField(
		default='House lights up',
		max_length = 200,
		help_text = "How does the show end? Is this indicated in a certain way?"
	)

	show_stop = models.ManyToManyField(
		ShowStop,
		blank=True,
		help_text="Please indicate the things that <strong>occur during the show</strong>"
	)
	show_stop_notes = models.TextField(
		blank=True,
		help_text="If there are any Show Stop Triggers, provide details about them here."
	)
	shown_spaces = models.BooleanField(
		default=False,
		help_text = "Have you shown the company around the theatre, showing them the areas they can use?"
	)
	performers_pass = models.BooleanField(
		default=False,
		help_text = "Have you informed the company that they can see all the shows today at a discounted rate?"
	)

	timestamp = models.DateTimeField(
		auto_now=True,
	)
	def __str__(self):
		display_string = 'Show Details: ' + str(self.show_name)
		return display_string

class VenueReport(models.Model):
	show_name = models.OneToOneField(
		Show,
		on_delete=models.CASCADE,
	)
	slot_start = models.TimeField(blank=True, null=True)
	get_in_notes = models.TextField(blank=True, null=True)
	house_open = models.TimeField(blank=True, null=True)
	performance_start = models.TimeField(blank=True, null=True)
	performance_notes = models.TextField(blank=True, null=True)
	performance_end = models.TimeField(blank=True, null=True)
	house_clear = models.TimeField(blank=True, null=True)
	get_out_notes = models.TextField(blank=True, null=True)
	slot_end = models.TimeField(blank=True, null=True)
	venue_notes = models.TextField(blank=True, null=True, help_text="General notes")

	def __str__(self):
		display_string = 'Venue Report for ' + str(self.show_name)
		return display_string

class FOHReport(models.Model):
	class Meta:
		verbose_name_plural = "FOH Reports"
		verbose_name = "FOH Report" 

	show_name = models.OneToOneField(
		Show,
		on_delete = models.CASCADE
	)

	audience_behaviour = models.TextField(blank=True)
	foyer_atmosphere = models.TextField(blank=True)

	def __str__(self):
		display_string = 'Front of House report for ' + str(self.show_name)
		return display_string

class DayReport(models.Model):
	class Meta:
		ordering = ['-date']

	date = models.DateField(
		unique=True, 
	)
	auditorium_bar_sales = models.IntegerField(blank=True, null=True)
	studio_bar_sales = models.IntegerField(blank=True, null=True)
	vendor_notes = models.TextField(
		blank=True,
		help_text = "Include each vendor, their day's takings, and any other notes"
	)
	weather = models.CharField(
		blank=True,
		max_length = 200,
	)
	overall_atmosphere = models.TextField(blank=True)
	approx_footfall = models.IntegerField(blank=True, null=True)
	notes = models.TextField(
		blank=True,
		help_text = "Any other points worth noting from the day."
	)

	def __str__(self):
		display_string = 'Day report for ' + str(self.date)
		return display_string

class LogReport(models.Model):
	class Meta:
		ordering = ['-report_date']

	report_type = models.CharField(
		max_length = 50,
		choices = (
			('A', 'Accident'),
			('I', 'Incident'),
			('C', 'Complaint'),
			('N', 'Note'),
		)
	)
	show_name = models.ForeignKey(
		Show, default=None, null=True, blank=True, on_delete=models.CASCADE,
		help_text = "If this log entry is to do with a show, select which one.")
	company_name = models.ForeignKey(
		Company, default=None, null=True, blank=True, on_delete=models.CASCADE,
		help_text = "If this log entry is to do with a company, select which one.")
	author_name = models.CharField(
		max_length=100,
	)
	subject_name = models.CharField(
		max_length=100,
		help_text = "Who, if anyone, is this report about?",
		blank=True,
	)
	report_text = models.TextField(
		help_text = "Festival log entries are only visible to the management team, and will be kept confidential where necessary. Please provide as much detail as possible."
	)
	report_date = models.DateTimeField()

	def __str__(self):
		display_string = str(self.get_report_type_display()) + ' report'
		if self.show_name is not None or self.company_name is not None:
			display_string = display_string + ' about '
			if self.show_name is not None:
				display_string = display_string + str(self.show_name)
			if self.show_name is not None and self.company_name is not None:
				display_string = display_string + ' and '
			if self.company_name is not None:
				display_string = display_string + str(self.company_name)
		display_string = display_string + ' by ' + str(self.author_name)

		return display_string

stuff/forms.py
from django import forms 
from .widgets import CustomTimePicker
from stuff.models import *

class RequirementForm(forms.ModelForm):
	class Meta:
		model = Requirement 
		fields = '__all__'

class InductionForm(forms.ModelForm):
	class Meta:
		model = Induction 
		fields = '__all__'
		exclude = {
			'timestamp'
		}
		widgets = {
			'show_phone': forms.widgets.TextInput(),
				## TODO: Don't strip starting 0
			'show_stop': forms.widgets.CheckboxSelectMultiple(),
		}

	# show_name = Show.objects.filter(has_induction is not None)
	# Change field.show_name to be Show.objects.filter(has_induction=False)
	# Set field.show_name to be read-only when editing (as below, potentially)
			# def __init__(self, *args, **kwargs):
			#     request = kwargs.pop("request", None)
			#     super(FOHReportForm, self).__init__(*args, **kwargs)
			#     instance = getattr(self, 'instance', None)
			#     if instance and instance.pk:
			#         self.fields.pop('show_name')

class VenueReportForm(forms.ModelForm):
	class Meta:
		model = VenueReport 
		fields = '__all__'
		exclude = { 'timestamp '}

	# Make the timepicker appear for all time-based fields automagically 
	def __init__(self, *args, **kwargs):
		super(VenueReportForm, self).__init__(*args, **kwargs)
		for key, value in self.fields.items():
			if key in ['slot_start', 'house_open', 'performance_start', 'performance_end',
			'house_clear', 'slot_end']:
				self.fields[key].widget = CustomTimePicker()

class FOHReportForm(forms.ModelForm):
	class Meta:
		model = FOHReport 
		fields = '__all__'
		exclude = { 'timestamp '}

class LogReportForm(forms.ModelForm):
	class Meta:
		model = LogReport  
		fields = '__all__'
		exclude = { 'report_date' }

class DayReportForm(forms.ModelForm):
	class Meta:
		model = DayReport 
		fields = '__all__'
		

stuff/templates/stuff/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<!-- <head> section of pages -->
	<head> 
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}Title{% endblock %} | StuFF</title>

		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600|Montserrat:400,500,600,700' rel='stylesheet' type='text/css'>

		<!-- Popper.js (for Bootstrap 4) -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

		<!-- JQuery -->
		<script
			src="https://code.jquery.com/jquery-3.2.1.min.js"
			integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			crossorigin="anonymous"></script>

		<!-- Bootstrap JS --> 
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		
		<!-- FontAwesome --> 
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'stuff/css/main.css' %}">

		{% if using_time %}
		<!-- MomentJS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

		<!-- Tempus Dominus Bootstrap 4 -->
		<!-- TODO: Improve styling of time widget; the below CDN breaks due to the table styling of the parent --> 
		<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" /> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

		{% endif %}

	</head>
	<body> 
		<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light mb-4">
			<div class="container">
		  	<div class="col">
		      <a class="navbar-brand" href="{% url 'stuff:stuffCurrentShows' %}">
		        <img src="{% static 'stuff/stuff-icon.png' %}" width=100px />
		      </a>
				  <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>
		    </div>
				<div class="collapse navbar-collapse" id="navigation">
					<ul class="navbar-nav mr-auto">
						{% if user.is_authenticated %}
						<div class="dropdown text-right">
							<li class="nav-item">
								<a href="#" class="dropdown-toggle nav-item nav-link" data-toggle="dropdown">Hi, {% if user.first_name %}{{ user.first_name|title }}{% else %}{{ user|title }}{% endif %}. <i class="caret"></i></a>
								<ul class="dropdown-menu">
									{% if user.is_staff %}
										<li><a href="/admin" class="dropdown-item">Admin</a></li>
									{% endif %}
									<li><a href="{% url 'stuff:stuffLogout' %}" class="dropdown-item">Logout</a></li>
								</ul>
							</li>
						</div>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'stuff:stuffLogin' %}">Login</a>
						</li>
						{% endif %}
						<div class="dropdown">
							<li class="nav-item">
								<a href="#" class="dropdown-toggle nav-item nav-link" data-toggle="dropdown">Shows <i class="caret"></i></a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffCurrentShows' %}">Upcoming</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffShowArchive' %}">All</a>
									</li>
								</ul>
							</li>
						</div>
						{% if user.is_staff %}
						<div class="dropdown">
							<li class="nav-item">
								<a href="#" class="dropdown-toggle nav-item nav-link" data-toggle="dropdown">New... <i class="caret"></i></a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffRequirementsBlankNew' %}">Requirements Form</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffInductionBlankNew' %}">Induction</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffFOHReportBlankNew' %}">FOH Report</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffVenueReportBlankNew' %}">Venue Report</a>
									</li>
								</ul>
							</li>
						</div>
						{% endif %}
						<div class="dropdown">
							<li class="nav-item">
								<a href="#" class="dropdown-toggle nav-item nav-link" data-toggle="dropdown">Festival Log <i class="caret"></i></a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffLogNew' %}">New Log Entry</a>
									</li>
									{% if user.is_staff %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffLogList' %}">View log entries</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffDayReportNew' %}">Add a daily report</a>
									</li>
									{% endif %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'stuff:stuffDayReportList' %}">View daily reports</a>
									</li>
								</ul>
							</li>
						</div>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			{% for message in messages %}
				<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					{% if message.tags == 'alert' %}<i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;
					{% else %}<i class="fa fa-fw fa-info-circle"></i>&nbsp;
					{% endif %}
					{{ message }}
				</div>
			{% endfor %}
			{% block content %}
				<p>No content defined.</p>
			{% endblock %}
			<hr>
			<div class="footer">
				<div class="row">
					<div class="col text-center text-muted small"><p><em>&copy; The Nottingham New Theatre, 2019</em></p></div>
				</div>
			</div>
		</div>
	</body>
</html>

stuff/templates/stuff/company-detail.html
{% extends 'stuff/base.html' %}
{% block title %}{{ company.name }}{% endblock %}

{% block content %}
<h1 class="text-center">
	{{ company.name }}
</h1>
<div class="row">
{% for show in company.company_shows %}
<div class="col-12">
	<div class="card mb-4">
		<div class="row">
			<div class="col px-1 mx-3 mr-sm-0 bg-light">
				{% include 'stuff/include/show_header.html' with company_page=1 show_list=1  %}
			</div>
			<div class="col-12 col-sm pl-sm-0">
				<div class="card-body p-0">
					{% include 'stuff/include/show_form_list.html' %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endfor %}
</div>
{% endblock %}

stuff/templates/stuff/login.html
{% extends 'stuff/base.html' %}
{% load widget_tweaks %}
{% block title %}Login{% endblock %}

{% block content %}
	{% if user.is_authenticated %}
		<div class="alert alert-warning text-center" role="alert">
			<p><i class="fa fa-fw fa-exclamation-circle"></i> You are already logged in. Would you like to <a href="{% url 'stuff:stuffLogout' %}" class="alert-link">logout</a>?</p>
			<p>You may have come to this page in error, or because your account does not have the privileges to do whatever it is you just tried.</p>
		</div>
	{% else %}
		<h1 class="text-center">Login</h1>
		{% if form.errors %}
			<div class="row">
				<div class="alert alert-danger col-8 mx-auto" role="alert"><i class="fa fa-exclamation fa-fw"></i> Incorrect username or password. Please try again.</div>
			</div>
		{% endif %}
		{% if next %} 
			{% if next != "/" %}
			<div class="row">
				<div class="alert alert-warning col-8 mx-auto" role="alert"><i class="fa fa-info fa-fw"></i> You need to log in to do that.</div>
			</div>
			{% endif %}
		{% endif %}
		{# Actual login form #}
		<div class="row">
			<div class="col">
				<form method="post" action="{% url 'stuff:stuffLogin' %}">
					{% csrf_token %}
					{% for field in form %}
						<div class="row form-group">
							<div class="col-lg-8 col-sm-10 col-12 mx-auto">
								<div class="text-left text-primary">{{ field.label_tag|title }}</div>
								{% render_field field class+="form-control" placeholder+=field.label %}
							</div>
						</div>
					{% endfor %}
					<div class="row">
						<div class="col-12 col-sm-10 col-lg-8 mx-auto">
							<button type="submit" value="login" class="btn btn-primary btn-lg btn-block">Login</button>
							<input type="hidden" name="next" value="{{ next }}" />
						</div>
					</div>
				</form>
			</div>
		</div>
	{% endif %}
{% endblock %}

stuff/templates/stuff/report-day-list.html
{% extends 'stuff/base.html' %}
{% block title %}Daily Reports{% endblock %}

{% block content %}
<div class="row">
	<div class="col-8 offset-2">
		<h1 class="text-center">Daily Reports</h1>
	</div>
	{% if user.is_staff %}
	<div class="col-2">
		<a class="btn btn-info" href="{% url 'stuff:stuffLogNew' %}"><i class="fa fa-plus"></i> New Entry</a>
	</div>
	{% endif %}
</div>
<hr>
<div class="row">
	<div class="col">
		{% if dayreport %}
		<dl>
			{% for report in dayreport %}
				<dt><a href="{% url 'stuff:stuffDayReport' report.pk %}">{{ report }}</a></dt>
			{% endfor %}
		</dl>
		{% else %}
			<p class="text-center text-muted"><i class="fa fa-info-circle"></i> There are no day reports yet.</i></p>
		{% endif %}
	</div>
</div>
{% endblock %}

stuff/templates/stuff/report-log-list.html
{% extends 'stuff/base.html' %}
{% block title %}Log Entries{% endblock %}

{% block content %}
<div class="row">
	<div class="col-8 offset-2">
		<h1 class="text-center">Log Entries</h1>
	</div>
	<div class="col-2">
		<a class="btn btn-info" href="{% url 'stuff:stuffLogNew' %}"><i class="fa fa-plus"></i> New Entry</a>
	</div>
</div>
<hr>
<div class="row">
	<div class="col">
		{% if logreport %}
		<dl>
			{% for log in logreport %}
				<dt><a href="{% url 'stuff:stuffLogSingle' log.pk %}">{{ log }}</a></dt>
				{% if log.subject %}<dd>Concerning {{ log.subject }}</dd>{% endif %}
				<dd>Submitted on {{ log.report_date }}</dd>
			{% endfor %}
		</dl>
		{% else %}
			<p class="text-center text-muted"><i class="fa fa-info-circle"></i> There are no entries in the log yet.</i></p>
		{% endif %}
	</div>
</div>
{% endblock %}