nt_stuff/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('stuff.urls')),
]

admin.site.site_header = "StuFF at the Nottingham New Theatre"
admin.site.site_title = "StuFF Admin"

stuff/urls.py
from django.urls import include, path 

from . import views 

app_name = 'stuff'
urlpatterns = [

	# Authentication
	#/login
	path('login/', views.stuffLoginView.as_view(), name='stuffLogin'),
	#/logout
	path('logout/', views.stuffLogoutView.as_view(), name='stuffLogout'),

	# Shows 
	path('', views.ShowView.as_view(), name='stuffCurrentShows'),
	path('show/', views.ShowView.as_view(), name='stuffCurrentShows'),
	path('show/all', views.ShowArchiveView.as_view(), name='stuffShowArchive'),
	path('show/<int:pk>/', views.InductionView.as_view(), name='stuffInduction'),
	path('show/<int:pk>/', include([
		path('start/', views.InductionNewView.as_view(), name='stuffInductionNew'),
		path('edit/', views.InductionEditView.as_view(), name='stuffInductionEdit'),
		path('requirements/', views.RequirementsView.as_view(), name='stuffRequirements'),
		path('requirements/new', views.RequirementsNewView.as_view(), name='stuffRequirementsNew'),
		path('requirements/edit', views.RequirementsEditView.as_view(), name='stuffRequirementsEdit'),
		path('venue/', views.VenueReportView.as_view(), name='stuffVenueReport'),
		path('venue/new', views.VenueReportNewView.as_view(), name='stuffVenueReportNew'),
		path('venue/edit', views.VenueReportEditView.as_view(), name='stuffVenueReportEdit'),
		path('foh/', views.FOHReportView.as_view(), name='stuffFOHReport'),
		path('foh/new', views.FOHReportNewView.as_view(), name='stuffFOHReportNew'),
		path('foh/edit', views.FOHReportEditView.as_view(), name='stuffFOHReportEdit'),
	])),

	path('company/<int:pk>', views.CompanyView.as_view(), name='stuffCompanySingle'),

	path('requirements', views.RequirementsNewView.as_view(), name='stuffRequirementsBlankNew'),
	path('induction', views.InductionNewView.as_view(), name='stuffInductionBlankNew'),
	path('venue', views.VenueReportNewView.as_view(), name='stuffVenueReportBlankNew'),
	path('foh', views.FOHReportNewView.as_view(), name='stuffFOHReportBlankNew'),

	path('log/', views.LogReportListView.as_view(), name='stuffLogList'),
	path('log/<int:pk>/', views.LogReportSingleView.as_view(), name='stuffLogSingle'),
	path('log/<int:pk>/edit', views.LogReportEditView.as_view(), name='stuffLogEdit'),
	path('log/new/', views.LogReportCreateView.as_view(), name='stuffLogNew'),

	path('log/day/', views.DayReportListView.as_view(), name='stuffDayReportList'),
	path('log/day/<int:pk>', views.DayReportView.as_view(), name='stuffDayReport'),
	path('log/day/<int:pk>/edit', views.DayReportEditView.as_view(), name='stuffDayReportEdit'),
	path('log/day/new', views.DayReportCreateView.as_view(), name='stuffDayReportNew'),

	# Festival Reports (TBA)
]
handler404 = views.PageNotFoundView.as_view()

stuff/models.py
import datetime

from django.db import models
from django.utils import timezone 

# Create your models here.

class Venue(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name 

class ShowStop(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		verbose_name = "Show Stop Trigger"

	def __str__(self):
		return self.name 

class Company(models.Model):
	class Meta:
		verbose_name_plural = "Companies"
	name = models.CharField(
		max_length=250,
		unique=True
	)

	def company_shows(self):
		return Show.objects.filter(company_name=self)

	def __str__(self):
		return self.name 

class Show(models.Model):
	class Meta:
		ordering = ['show_date','performance_start']
	company_name = models.ForeignKey(
		Company,
		on_delete=models.DO_NOTHING
	)

	show_name = models.CharField(max_length=250)

	performance_venue = models.ForeignKey(
		Venue,
		default=None,
		blank=True,
		on_delete=models.DO_NOTHING
	)

	ticketing_id = models.IntegerField(
		unique=True,
		blank=True,
		null=True,
		help_text = 'Go to the <a href="https://ticketing.newtheatre.org.uk/" target="_blank">Ticketing Site</a>, select a show and use the first number in the URL: /SHOWID/0.'
	)

	show_date = models.DateField(blank=True)
	slot_start = models.TimeField(blank=True)
	slot_end = models.TimeField(blank=True)
	performance_start = models.TimeField(blank=True)
	performance_end = models.TimeField(blank=True)

	def has_requirements(self):
		has_requirements = Requirement.objects.filter(show_name=self)
		return has_requirements

	def has_induction(self):
		has_induction = Induction.objects.filter(show_name=self)
		return has_induction

	def has_foh_report(self):
		has_foh_report = FOHReport.objects.filter(show_name=self)
		return has_foh_report

	def has_venue_report(self):
		has_venue_report = VenueReport.objects.filter(show_name=self)
		return has_venue_report

	def __str__(self):
		display_string = '"' + str(self.show_name) + '" by ' + str(self.company_name)
		return display_string

class Requirement(models.Model):
	class Meta:
		verbose_name = "Requirements Form"
		verbose_name_plural = "Requirements Forms"

	show_name = models.OneToOneField(
		Show,
		on_delete = models.CASCADE,
	)
	# Theatre
	using_workshop = models.BooleanField(
		default=False
	)
	using_storage = models.BooleanField(
		default=False
	)
	storage_notes = models.CharField(
		default='None',
		max_length=250,
		help_text = "What is this company bringing to store?",
	)
	using_props = models.BooleanField(default=False)
	prop_notes = models.CharField(
		default='None',
		max_length=250,
		help_text = "What props/costume is this show using from the Theatre?"
	)
	rigging = models.CharField(
		default='None',
		max_length = 250,
		help_text = "Any additional rigging that is required."
	)
	effects = models.CharField(
		default='None',
		max_length=200,
		help_text = "Effects used in this show, eg: strobe, smoke, haze, pyro."
	)
	fire_alarm_disabled = models.BooleanField(default=False)
	theatre_notes = models.TextField(blank=True)

	# Set/Staging
	seating_layout = models.CharField(
		choices = (
			('E', 'End-on'),
			('T', 'Thrust'),
			('R', 'In the round'),
			('O', 'Other (add in notes)'),
		),
		default = 'E',
		max_length = 50
	)
	set_details = models.CharField(
		default='No set',
		max_length=200
	)
	set_notes = models.TextField(blank=True)

	# Tech
	lighting = models.CharField(
		max_length=250,
		default='None',
	)
	sound = models.CharField(
		max_length=250,
		default='None',
	)
	microphones = models.IntegerField(default=0, help_text="How many microphones are being used?")
	video = models.CharField(
		max_length=250,
		default = 'None',
	)
	projector_screen = models.BooleanField(default=False, help_text="Does this show require a projector screen?")
	tech_notes = models.TextField(blank=True)

	def __str__(self):
		display_string = "Requirements form for " + str(self.show_name)
		return display_string

class Induction(models.Model):
	show_name = models.OneToOneField(
		Show,
		on_delete=models.CASCADE, 
	)
	author = models.CharField(
		max_length=100,
		help_text="Who is filling this form out?",
		# Should make this relate to a group of users 
	)
	show_member = models.CharField(
		max_length=100,
		help_text="Who are you speaking to?"
	)
	show_phone = models.IntegerField(
		help_text="What is their phone number?"
	) 
	show_role = models.CharField(
		max_length = 30,
		help_text="What is their role in the company?",
		blank=True
	)
	latecomers = models.CharField(
		max_length = 30,
		help_text = "May latecomers be permitted?",
		choices = (
			('N', 'No latecomers'),
			('Y', 'Latecomers up to the first 15 minutes of the show'),
		),
		default = 'N'
	)
	comps = models.IntegerField(
		default = 0
	)
	comp_list = models.TextField(
		blank=True,
		help_text = "Please list the full names of all people receiving complimentary tickets."
	)
	minimum_audience = models.CharField(
		default='No minimum',
		max_length=255,
		help_text = "Is there a minimum audience to which this company will perform?"
	)

	show_end = models.CharField(
		default='House lights up',
		max_length = 200,
		help_text = "How does the show end? Is this indicated in a certain way?"
	)

	show_stop = models.ManyToManyField(
		ShowStop,
		blank=True,
		help_text="Please indicate the things that <strong>occur during the show</strong>"
	)
	show_stop_notes = models.TextField(
		blank=True,
		help_text="If there are any Show Stop Triggers, provide details about them here."
	)
	shown_spaces = models.BooleanField(
		default=False,
		help_text = "Have you shown the company around the theatre, showing them the areas they can use?"
	)
	performers_pass = models.BooleanField(
		default=False,
		help_text = "Have you informed the company that they can see all the shows today at a discounted rate?"
	)

	timestamp = models.DateTimeField(
		auto_now=True,
	)
	def __str__(self):
		display_string = 'Show Details: ' + str(self.show_name)
		return display_string

class VenueReport(models.Model):
	show_name = models.OneToOneField(
		Show,
		on_delete=models.CASCADE,
	)
	slot_start = models.TimeField(blank=True, null=True)
	get_in_notes = models.TextField(blank=True, null=True)
	house_open = models.TimeField(blank=True, null=True)
	performance_start = models.TimeField(blank=True, null=True)
	performance_notes = models.TextField(blank=True, null=True)
	performance_end = models.TimeField(blank=True, null=True)
	house_clear = models.TimeField(blank=True, null=True)
	get_out_notes = models.TextField(blank=True, null=True)
	slot_end = models.TimeField(blank=True, null=True)
	venue_notes = models.TextField(blank=True, null=True, help_text="General notes")

	def __str__(self):
		display_string = 'Venue Report for ' + str(self.show_name)
		return display_string

class FOHReport(models.Model):
	class Meta:
		verbose_name_plural = "FOH Reports"
		verbose_name = "FOH Report" 

	show_name = models.OneToOneField(
		Show,
		on_delete = models.CASCADE
	)

	audience_behaviour = models.TextField(blank=True)
	foyer_atmosphere = models.TextField(blank=True)

	def __str__(self):
		display_string = 'Front of House report for ' + str(self.show_name)
		return display_string

class DayReport(models.Model):
	class Meta:
		ordering = ['-date']

	date = models.DateField(
		unique=True, 
	)
	auditorium_bar_sales = models.IntegerField(blank=True, null=True)
	studio_bar_sales = models.IntegerField(blank=True, null=True)
	vendor_notes = models.TextField(
		blank=True,
		help_text = "Include each vendor, their day's takings, and any other notes"
	)
	weather = models.CharField(
		blank=True,
		max_length = 200,
	)
	overall_atmosphere = models.TextField(blank=True)
	approx_footfall = models.IntegerField(blank=True, null=True)
	notes = models.TextField(
		blank=True,
		help_text = "Any other points worth noting from the day."
	)

	def __str__(self):
		display_string = 'Day report for ' + str(self.date)
		return display_string

class LogReport(models.Model):
	class Meta:
		ordering = ['-report_date']

	report_type = models.CharField(
		max_length = 50,
		choices = (
			('A', 'Accident'),
			('I', 'Incident'),
			('C', 'Complaint'),
			('N', 'Note'),
		)
	)
	show_name = models.ForeignKey(
		Show, default=None, null=True, blank=True, on_delete=models.CASCADE,
		help_text = "If this log entry is to do with a show, select which one.")
	company_name = models.ForeignKey(
		Company, default=None, null=True, blank=True, on_delete=models.CASCADE,
		help_text = "If this log entry is to do with a company, select which one.")
	author_name = models.CharField(
		max_length=100,
	)
	subject_name = models.CharField(
		max_length=100,
		help_text = "Who, if anyone, is this report about?",
		blank=True,
	)
	report_text = models.TextField(
		help_text = "Festival log entries are only visible to the management team, and will be kept confidential where necessary. Please provide as much detail as possible."
	)
	report_date = models.DateTimeField()

	def __str__(self):
		display_string = str(self.get_report_type_display()) + ' report'
		if self.show_name is not None or self.company_name is not None:
			display_string = display_string + ' about '
			if self.show_name is not None:
				display_string = display_string + str(self.show_name)
			if self.show_name is not None and self.company_name is not None:
				display_string = display_string + ' and '
			if self.company_name is not None:
				display_string = display_string + str(self.company_name)
		display_string = display_string + ' by ' + str(self.author_name)

		return display_string

stuff/forms.py
from django import forms 
from .widgets import CustomTimePicker
from stuff.models import *

class RequirementForm(forms.ModelForm):
	class Meta:
		model = Requirement 
		fields = '__all__'

class InductionForm(forms.ModelForm):
	class Meta:
		model = Induction 
		fields = '__all__'
		exclude = {
			'timestamp'
		}
		widgets = {
			'show_phone': forms.widgets.TextInput(),
				## TODO: Don't strip starting 0
			'show_stop': forms.widgets.CheckboxSelectMultiple(),
		}

	# show_name = Show.objects.filter(has_induction is not None)
	# Change field.show_name to be Show.objects.filter(has_induction=False)
	# Set field.show_name to be read-only when editing (as below, potentially)
			# def __init__(self, *args, **kwargs):
			#     request = kwargs.pop("request", None)
			#     super(FOHReportForm, self).__init__(*args, **kwargs)
			#     instance = getattr(self, 'instance', None)
			#     if instance and instance.pk:
			#         self.fields.pop('show_name')

class VenueReportForm(forms.ModelForm):
	class Meta:
		model = VenueReport 
		fields = '__all__'
		exclude = { 'timestamp '}

	# Make the timepicker appear for all time-based fields automagically 
	def __init__(self, *args, **kwargs):
		super(VenueReportForm, self).__init__(*args, **kwargs)
		for key, value in self.fields.items():
			if key in ['slot_start', 'house_open', 'performance_start', 'performance_end',
			'house_clear', 'slot_end']:
				self.fields[key].widget = CustomTimePicker()

class FOHReportForm(forms.ModelForm):
	class Meta:
		model = FOHReport 
		fields = '__all__'
		exclude = { 'timestamp '}

class LogReportForm(forms.ModelForm):
	class Meta:
		model = LogReport  
		fields = '__all__'
		exclude = { 'report_date' }

class DayReportForm(forms.ModelForm):
	class Meta:
		model = DayReport 
		fields = '__all__'
		

stuff/templates/stuff/include/show_buttons.html
<div class="row mb-2">
	{% if report %}
	<div class="col">
		<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffInduction' show.pk %}">View Show Induction Notes</a>
	</div>
	{% endif %}
	{% if report != "requirements" %}
	<div class="col">
		{% if show.has_requirements %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffRequirements' show.pk %}">View Changeover Notes</a>
		{% elif user.is_staff %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffRequirementsNew' show.pk %}">Add Requirements</a>
		{% else %}
			<a class="btn btn-outline-info btn-block btn-lg disabled" role="button">No changeover notes given</a>
		{% endif %}
	</div>
	{% endif %}
	{% if report != "foh" %}
	<div class="col">
		{% if show.has_foh_report %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffFOHReport' show.pk %}">View Front of House report</a>
		{% elif user.is_staff %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffFOHReportNew' show.pk %}">Add Front of House report</a>
		{% else %}
			<a class="btn btn-outline-info btn-block btn-lg disabled" role="button">No front of house report available</a>
		{% endif %}
	</div>
	{% endif %}
	{% if report != "venue" %}
	<div class="col">
		{% if show.has_venue_report %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffVenueReport' show.pk %}">View Venue report</a>
		{% elif user.is_staff %}
			<a class="btn btn-outline-info btn-block btn-lg" role="button" href="{% url 'stuff:stuffVenueReportNew' show.pk %}">Add Venue report</a>
		{% else %}
			<a class="btn btn-outline-info btn-block btn-lg disabled" role="button">No venue report available</a>
		{% endif %}
	</div>
	{% endif %}
</div>

stuff/templates/stuff/include/show_form_list.html
			<div class="row"><div class="col">
				{% if not show.has_induction %}
					{% if user.is_staff %}
						<a class="btn btn-block btn-info h5 pt-2 rounded-0 mb-0" href="{% url 'stuff:stuffInductionNew' show.pk %}"><i class="fa fa-plus fa-fw"></i> Fill out the induction form for this show</a>
					{% else %}
						<p class="text-center text-muted my-2"><em><i class="fa fa-info-circle fa-fw"></i> This show has not had its festival induction yet.</em></p>
					{% endif %}
				{% else %}
					<a class="btn btn-block btn-info h5 pt-2 rounded-0 mb-0" href="{% url 'stuff:stuffInduction' show.pk %}"><i class="fa fa-info-circle fa-fw"></i> View Show Induction details</a>
				{% endif %}
			</div></div>
			<div class="row"><div class="col">
				{% if not show.has_requirements %}
					{% if user.is_staff %}
						<a class="btn btn-success btn-block h5 pt-2 rounded-0 mb-0" href="{% url 'stuff:stuffRequirementsNew' show.pk %}"><i class="fa-fw fa fa-plus"></i> Add Changeover Requirements</a>
					{% else %}
						<p class="text-center text-muted my-2"><em><i class="fa fa-info-circle fa-fw"></i> There are no changeover plans for this show yet.</em></p>
					{% endif %}
				{% else %}
					<a class="btn btn-success btn-block h5 pt-2 rounded-0 mb-0" href="{% url 'stuff:stuffRequirements' show.pk %}">View Changeover Plan</a>
				{% endif %}
			</div></div>

			{% if show.has_induction %}
				{% if not show.has_foh_report %}
					{% if user.is_staff %}
						<div class="row">
							<div class="col"><a class="btn btn-block h5 pt-2 rounded-0 mb-0 btn-light" href="{% url 'stuff:stuffFOHReportNew' show.pk %}"><i class="fa-fw fa fa-plus"></i> Create Front of House Report</a></div>
						</div>
					{% endif %}
				{% else %}
					<div class="row px-2 mt-2">
						<div class="col-auto pt-2">Front of House Report</div>
						<div class="col text-right float-right"><a class="btn btn-warning h5 pt-2" href="{% url 'stuff:stuffFOHReport' show.pk %}"><i class="fa fa-fw  fa-eye"></i></a>{% if user.is_staff %}&nbsp;<a class="btn btn-warning h5 pt-2" href="{% url 'stuff:stuffFOHReportEdit' show.pk %}"><i class="fa fa-fw  fa-edit"></i></a>{% endif %}</div>
					</div>
				{% endif %}
				<hr class="mt-2">
				{% if not show.has_venue_report %}
					{% if user.is_staff %}
						<div class="row">
							<div class="col"><a class="btn btn-block h5 pt-2 rounded-0 mb-0 btn-light" href="{% url 'stuff:stuffVenueReportNew' show.pk %}"><i class="fa-fw fa fa-plus"></i> Create Venue Report</a></div>
						</div>
					{% endif %}
				{% else %}
				<div class="row px-2 mt-2">
					<div class="col-auto pt-2">Venue Report</div>
					<div class="col text-right float-right"><a class="btn btn-warning h5 pt-2" href="{% url 'stuff:stuffVenueReport' show.pk %}"><i class="fa fa-fw  fa-eye"></i></a>{% if user.is_staff %}&nbsp;<a class="btn btn-warning h5 pt-2" href="{% url 'stuff:stuffVenueReportEdit' show.pk %}"><i class="fa fa-fw  fa-edit"></i></a>{% endif %}</div>
				</div>
				{% endif %}
			{% else %}
				{% if user.is_staff %}
					<div class="col mt-2"><p class="text-center text-muted"><em><i class="fa fa-info-circle fa-fw"></i> Front of House and Venue Reports can be added once the show has completed its induction.</em></p></div>
				{% endif %}
			{% endif %}	

stuff/templates/stuff/include/show_header.html
	<div class="{% if show_list %}my-2{% else %}mr-5{% endif %}">
		{% if not datetime_only %}
		<div class="text-center">
			<h2>
				"{{ show.show_name }}"
				{% if not company_page %}<br /><small><a href="{% url 'stuff:stuffCompanySingle' show.company_name.pk %}">{{ show.company_name }}</a></small>{% endif %}
			</h2>
			<h4>{{ show.show_date }} | {{ show.performance_venue }}</h4>
		</div>
		{% endif %}
		<div class="row h5">
			<div class="col{% if show_list %}-auto col-md-6{% endif %} text-right"><strong>Slot: </strong></div><div class="col{% if show_list %}-auto col-md{% endif %}">{{ show.slot_start }} - {{ show.slot_end }}</div>
		</div>
		<div class="row h5">
			<div class="col{% if show_list %}-auto col-md-6{% endif %} text-right"><strong>Performance: </strong></div><div class="col{% if show_list %}-auto col-md{% endif %}">{{ show.performance_start }} - {{ show.performance_end }}</div>
		</div>
	</div>